### PR TITLE
5-Step Launch Wizard

### PR DESCRIPTION
**Pull request by acrdlph**
just a few loose ends left here: help popovers are missing, review step only shows 1 service and prompt texts are not perfect yet.

### CODE REVIEW

**Comment by acrdlph** [comment]
I think its ready! Hope I gitignored the right thing..

**Comment by acrdlph** [comment]
took the fix note for #82 out again, since i will still have to do some work on that

**Comment by lsaether** [comment]
The 6 lines starting here https://github.com/convergentcx/Arena/blob/master/src/build/contracts/PersonalEconomyFactory.json#L1519

**Comment by acrdlph** [comment]
something weird is going on here.. the build files in the pushed repo are different from the ones i have locally ?!

**Comment by lsaether** [comment]
You copied the `PersonalEconomyFactory` to `PersonalEconomy` artifact file xD

Also I'm in appear if you want to join

**Comment by acrdlph** [comment]
argh yea got it now!

**Pull request merged**
